# Generated by Django 2.2.3 on 2019-08-08 10:01

import apps.api.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_samples', models.PositiveIntegerField(default=0)),
                ('total_classes', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'available'), ('pending', 'pending')], max_length=15)),
                ('classes', djongo.models.fields.ArrayModelField(model_container=apps.api.core.models.StringObject)),
                ('domain', models.CharField(default='General', max_length=30)),
                ('dataset_type', models.CharField(choices=[('object detection', 'object detection'), ('classification', 'classification')], default='classification', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
