# Generated by Django 2.2.3 on 2019-08-09 09:49

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_auto_20190808_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiondataset',
            name='classes',
        ),
        migrations.AddField(
            model_name='visiondataset',
            name='labels',
            field=djongo.models.fields.ListField(default=[]),
        ),
        migrations.AlterField(
            model_name='visiondataset',
            name='dataset_type',
            field=models.SmallIntegerField(choices=[(0, 'Classification'), (1, 'Object Detection'), (2, 'Segmentation')], default=0),
        ),
        migrations.AlterField(
            model_name='visiondataset',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Pending'), (2, 'Error')], default=0),
        ),
    ]
