# Generated by Django 2.2.3 on 2019-08-26 10:40

import apps.api.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vision', '0003_auto_20190809_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionDLModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('metrics', djongo.models.fields.ArrayModelField(model_container=apps.api.core.models.Metrics)),
                ('model_type', models.SmallIntegerField(choices=[(0, 'Classification'), (1, 'Object Detection'), (2, 'Segmentation')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
