from .ds_views import VisionDatasetAPIView, VisionDatasetDetailAPIView
from .md_views import VisionDLModelAPIView, VisionDLModelDetailAPIView
from .tasks_views import CeleryAPIVIew, CheckProcessAPIView