# Generated by Django 2.2.3 on 2019-08-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subsciption',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Premium'), ('E', 'Enterprise')], default='F', max_length=1),
        ),
    ]
